### ISSUE TITLE
[Question] how does this differ from appsettings?

### ISSUE THREAD

**Issue by kot91** [DotNetCraft/ConfigurationParser#1]
Using the ConfigurationManager class from system.configuration (including the configuration dll as a project reference) you can directly interact with the app.config file.

ex.
`var somevalue= ConfigurationManager.AppSettings["keyFromAppSettings"];`

and the in app.config
`    <add key="keyFromAppSettings"  value="somevalue" />`

So how does this project differ from this class?

Also, I understand you are just using it as an example, but it's typically not a good idea to reference login credentials from a plain text format. better to use GAC, hardcode the credentials or set up a databind.

ConfigurationManager ref:
https://msdn.microsoft.com/en-us/library/system.configuration.configurationmanager(v=vs.110).aspx

**Comment by DotNetCraft** [comment]
Thank you for your question.
First of all, we should understand how we are going to use settings in our system. Let's image that we want to store connection string in app.config.
```
<add key="ConnectionString" value="someSqlUrl" />
```
Thus, in our system we have to create something where we will store this information. In a very small project it can be just a variable, but in big projects it should be separate class (say DatabaseSettings) which we will put into the DI container and reuse whereever we need. Thus, our code using ConfigurationManager will be:
```
DatabaseSettings dbConfig = new DatabaseSettings();
dbConfig.ConnectionString = ConfigurationManager.AppSettings["ConnectionString"];
```
Now image that we have several databases and other settings. In this case we have to write additional lines of ConfigurationManager.AppSettings["..."].
Using this library, you just create a necessary classes and 
```
var dbConfig  = (DatabaseSettings)(dynamic)ConfigurationManager.GetSection("DatabaseSettings");
```
That's it.

**Comment by kot91** [comment]
That's actually a problem I have with one of my projects! Great idea!

If you need any help in developing this further I would love to assist (I've had to write an xml parser for a separate goal)!

**Comment by DotNetCraft** [comment]
No worries

If you find some bugs just et me know...
